/*
 * Copyright 2026 Mirko Dimartino
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.mirkoddd.sift.core.engine;

import java.util.*;
import java.util.function.Consumer;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.regex.PatternSyntaxException;
import java.util.stream.Stream;
import java.util.stream.StreamSupport;

/**
 * The default execution engine for Sift, powered by standard {@code java.util.regex}.
 * <p>
 * This engine supports all regex features generated by the Sift DSL and serves as the
 * backbone for the library's zero-dependency guarantee.
 *
 * @since 6.0.0
 */
public final class JdkEngine implements SiftEngine {

    /**
     * Stateless singleton instance of the JDK Engine.
     */
    public static final JdkEngine INSTANCE = new JdkEngine();

    private JdkEngine() {
        // Prevent instantiation
    }

    /**
     * {@inheritDoc}
     * <p>
     * <b>Implementation Note:</b> As the reference implementation, this engine
     * supports the entire {@link RegexFeature} set.
     */
    @Override
    public SiftCompiledPattern compile(String rawRegex, Set<RegexFeature> usedFeatures) {

        checkSupport(usedFeatures);

        try {
            Pattern jdkPattern = Pattern.compile(rawRegex);
            return new JdkCompiledPattern(jdkPattern, rawRegex);
        } catch (PatternSyntaxException e) {
            throw new IllegalStateException("Sift generated an invalid regex syntax: " + rawRegex, e);
        }
    }

    /**
     * Internal implementation of the compiled pattern using standard JDK {@link Matcher}.
     */
    private static final class JdkCompiledPattern implements SiftCompiledPattern {

        private final Pattern pattern;
        private final String rawRegex;

        private JdkCompiledPattern(Pattern pattern, String rawRegex) {
            this.pattern = pattern;
            this.rawRegex = rawRegex;
        }

        /**
         * {@inheritDoc}
         */
        @Override
        public boolean containsMatchIn(CharSequence input) {
            if (input == null) return false;
            return pattern.matcher(input).find();
        }

        /**
         * {@inheritDoc}
         */
        @Override
        public boolean matchesEntire(CharSequence input) {
            if (input == null) return false;
            return pattern.matcher(input).matches();
        }

        /**
         * {@inheritDoc}
         */
        @Override
        public Optional<String> extractFirst(CharSequence input) {
            if (input == null) return Optional.empty();
            Matcher matcher = pattern.matcher(input);
            return matcher.find() ? Optional.of(matcher.group()) : Optional.empty();
        }

        /**
         * {@inheritDoc}
         */
        @Override
        public List<String> extractAll(CharSequence input) {
            if (input == null) return Collections.emptyList();
            Matcher matcher = pattern.matcher(input);
            List<String> results = new ArrayList<>();
            while (matcher.find()) {
                results.add(matcher.group());
            }
            return Collections.unmodifiableList(results);
        }

        /**
         * {@inheritDoc}
         */
        @Override
        public String replaceFirst(CharSequence input, String replacement) {
            if (input == null) return "";
            return pattern.matcher(input).replaceFirst(replacement);
        }

        /**
         * {@inheritDoc}
         */
        @Override
        public String replaceAll(CharSequence input, String replacement) {
            if (input == null) return "";
            return pattern.matcher(input).replaceAll(replacement);
        }

        /**
         * {@inheritDoc}
         * <p>
         * <b>Implementation Note (Java 8 Support):</b> Native extraction of group names
         * is not supported by the {@code Matcher} API in early Java versions. This implementation
         * safely parses the generated pattern string to discover the defined group names and
         * maps them to their matched values.
         */
        @Override
        public Map<String, String> extractGroups(CharSequence input) {
            if (input == null) return Collections.emptyMap();

            Matcher matcher = pattern.matcher(input);
            if (!matcher.find()) {
                return Collections.emptyMap();
            }

            Map<String, String> extractedGroups = new HashMap<>();
            Matcher nameExtractor = Pattern.compile("\\(\\?<([a-zA-Z][a-zA-Z0-9]*)>").matcher(rawRegex);

            while (nameExtractor.find()) {
                String groupName = nameExtractor.group(1);
                try {
                    String matchValue = matcher.group(groupName);
                    if (matchValue != null) {
                        extractedGroups.put(groupName, matchValue);
                    }
                } catch (IllegalArgumentException e) {
                    // Defensive catch: ignores malformed or uncaptured group names
                }
            }
            return Collections.unmodifiableMap(extractedGroups);
        }

        /**
         * {@inheritDoc}
         * <p>
         * <b>Implementation Note (Java 8 Support):</b> Relies on regex string parsing
         * to discover group names, ensuring backwards compatibility for environments
         * lacking native named-group extraction.
         */
        @Override
        public List<Map<String, String>> extractAllGroups(CharSequence input) {
            if (input == null) return Collections.emptyList();

            Matcher matcher = pattern.matcher(input);
            Matcher nameExtractor = Pattern.compile("\\(\\?<([a-zA-Z][a-zA-Z0-9]*)>").matcher(rawRegex);

            List<String> groupNames = new ArrayList<>();
            while (nameExtractor.find()) {
                groupNames.add(nameExtractor.group(1));
            }

            List<Map<String, String>> results = new ArrayList<>();
            while (matcher.find()) {
                Map<String, String> groups = new HashMap<>();
                for (String name : groupNames) {
                    try {
                        String value = matcher.group(name);
                        if (value != null) groups.put(name, value);
                    } catch (IllegalArgumentException e) {
                        // Defensive catch
                    }
                }
                results.add(Collections.unmodifiableMap(groups));
            }
            return Collections.unmodifiableList(results);
        }

        /**
         * {@inheritDoc}
         */
        @Override
        public List<String> splitBy(CharSequence input) {
            if (input == null) return Collections.emptyList();
            return Arrays.asList(pattern.split(input));
        }

        /**
         * {@inheritDoc}
         * <p>
         * <b>Implementation Note:</b> Uses a custom {@link Spliterator} to provide lazy
         * {@code Matcher.find()} evaluation, maintaining compatibility with Java 8 streams.
         */
        @Override
        public Stream<String> streamMatches(CharSequence input) {
            if (input == null) return Stream.empty();

            Matcher matcher = pattern.matcher(input);
            Spliterator<String> lazySpliterator = new Spliterators.AbstractSpliterator<String>(
                    Long.MAX_VALUE, Spliterator.ORDERED | Spliterator.NONNULL) {
                @Override
                public boolean tryAdvance(Consumer<? super String> action) {
                    if (matcher.find()) {
                        action.accept(matcher.group());
                        return true;
                    }
                    return false;
                }
            };
            return StreamSupport.stream(lazySpliterator, false);
        }

        /**
         * {@inheritDoc}
         */
        @Override
        public String getRawRegex() {
            return rawRegex;
        }
    }
}