/*
 * Copyright 2026 Mirko Dimartino
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.mirkoddd.sift.core.engine;

import java.util.Set;

/**
 * The core Service Provider Interface (SPI) for regex execution engines in the Sift library.
 * <p>
 * A {@code SiftEngine} acts as a bridge between the Sift DSL and the underlying
 * regular expression evaluator (e.g., standard JDK, RE2J, GraalVM TRegex).
 * Its primary responsibility is to validate the generated regex against the engine's
 * capabilities and compile it into an executable {@link SiftCompiledPattern}.
 * <p>
 * <b>Architectural Note for Implementors:</b>
 * It is highly recommended to extend {@link AbstractSiftEngine} rather than implementing
 * this interface directly. The abstract base class enforces the Template Method pattern,
 * guaranteeing that feature validation is strictly and automatically applied before
 * compilation, thus preventing accidental contract violations or runtime crashes.
 *
 * @see AbstractSiftEngine
 * @see SiftCompiledPattern
 * @since 6.0.0
 */
public interface SiftEngine {

    /**
     * Compiles the raw regular expression into an executable pattern.
     * <p>
     * <b>Contract:</b> Implementations MUST ensure that {@link #checkSupport(Set)}
     * is invoked and successfully passes before delegating the compilation to the
     * underlying engine.
     *
     * @param rawRegex     the raw regular expression string generated by the Sift DSL
     * @param usedFeatures the set of advanced regex features required by this pattern
     * @return a compiled, ready-to-use {@link SiftCompiledPattern}
     * @throws UnsupportedOperationException if the regex relies on a feature not supported by this engine
     * @throws IllegalArgumentException      if the underlying engine rejects the generated syntax
     * (e.g., due to engine-specific limitations or malformed generation)
     */
    SiftCompiledPattern compile(String rawRegex, Set<RegexFeature> usedFeatures);

    /**
     * Validates whether the requested regex features are supported by this specific engine.
     * <p>
     * This method acts as a fail-fast mechanism. Different engines have different
     * limitations (e.g., RE2J restricts lookarounds to guarantee linear time,
     * while GraalVM restricts certain anchors).
     *
     * @param features the set of regex features utilized in the current pattern
     * @throws UnsupportedOperationException if at least one feature in the set is explicitly
     * unsupported by the engine's implementation
     */
    void checkSupport(Set<RegexFeature> features);
}