/*
 * Copyright 2026 Mirko Dimartino
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.mirkoddd.sift.core.engine;

import java.util.Set;

/**
 * Represents the Service Provider Interface (SPI) for compiling regex strings
 * into executable matchers.
 * <p>
 * <b>Architectural Note:</b> This interface decouples pattern construction from execution.
 * To ensure system stability, implementations should validate the requested features
 * before attempting compilation.
 *
 * @since 6.0.0
 */
@FunctionalInterface
public interface SiftEngine {

    /**
     * Compiles the raw regular expression into an executable pattern.
     *
     * @param rawRegex     The regex string generated by the DSL.
     * @param usedFeatures An unmodifiable set of advanced features detected during assembly.
     * @return A thread-safe, compiled pattern ready for matching operations.
     */
    SiftCompiledPattern compile(String rawRegex, Set<RegexFeature> usedFeatures);

    /**
     * Validates if the engine supports all provided regex features.
     * <p>
     * <b>Fail-Fast Note:</b> This method provides a standard mechanism to verify
     * compatibility before execution. Engines that do not support a feature
     * <b>must</b> throw an {@link UnsupportedOperationException}.
     *
     * @param features The set of features to validate.
     * @throws UnsupportedOperationException if a feature is not supported.
     */
    default void checkSupport(Set<RegexFeature> features) {
        // Default implementation assumes full support (standard for JdkEngine).
    }
}