name: Sift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '11', '17', '21' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDKs
        uses: actions/setup-java@v5
        with:
          java-version: |
            ${{ matrix.java }}
            17
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Run Tests
        env:
          MATRIX_JAVA_VERSION: ${{ matrix.java }}
        run: ./gradlew build jacocoTestReport

      - name: Generate Jacoco Badge
        if: ${{ matrix.java == '17' }}
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: sift-core/build/reports/jacoco/test/jacocoTestReport.csv sift-annotations/build/reports/jacoco/test/jacocoTestReport.csv
          badges-directory: .github/badges
          generate-branches-badge: false

      - name: Commit and Push Badge
        if: ${{ github.event_name == 'push' && matrix.java == '17' }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .github/badges/
        
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "chore: update coverage badge [skip ci]"
            git push
          else
            echo "Coverage unchanged. No badge update needed."
          fi